apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: jeetlinux/docker-demo:loginapp

          ports:
            - containerPort: 5000
            
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer


